language: node_js
node_js:
- 10.19.0
- 12.16.1
- lts/* # current LTS version
- node # current stable - we *should* work with this, but allowed to fail

matrix:
  allow_failures: # https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail
    - node_js: node # allow current stable to fail

sudo: false
script:
- npm install
- "./node_modules/.bin/eslint ./lib"
- npm test
- ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

notifications:
  slack:
    on_success: always
    on_failure: always
    on_start: never
    rooms:
      secure: tEC0voqIsLZ7saaJlbS1vinS6CeoPivHsMcqmAcibM3bwhPWD4ueQdEqKf93BG3R0DeFDU7NoCb2nN8Oyrtq89N9zVEpD4tzAQChQymUUfxF3/WTXzX6Ifubm8fi7HgJHROWC04aFSTf1HUFyh1GWxgtQ8j6DsV+E5vEn3pqHRmaNRl0UXJta49qU2OXJVdBzIYOhMhZMJaVZPGhbBIfKzhTjz6h8nxg/qbpm3TNbHXZmjBtMJs7Ru84u2/BEAdz7/we4PExi2woSPWHmdHWEuvvSk1ZMEP47unI1UvZ69bjBsAV7H8OhbTygfILnjkiJbawVGAgZ1+n2ztc6SI5PbgB50hKCgW6qwH+7fkDsXetEwEe6NACOozuG2SbRUHNhKcDdpy4JrdA17Z2FikmET1hzcve5ZCw+bV1sCISpXTYNkWLqQGkm/5VdFlvdgB2uPXq9h9gnY1gRjI5MLZ1GzF0WwTDqKPBKhhZFho7oyBZS6pdOOp0+yN/Pu3qKUl97sWBw/usJTpO6jNWQPqV5ItQOjlUc6/5T9TJjtXdaI+H0kNbHQTlyaha1uywt/3JG8OZLx1e4wLPz+CFpR0eWghRlQcZBU9YsyFUrPN8hxKcUTGHCBseSNXTkl9m08toQJKRmIJ0QOXjLR5MFIkMoO+O7eyuE7FKYcl0tt/YFbQ=
deploy:
  provider: npm
  email: casey.macpherson@gettyimages.com
  api_key:
    secure: xKnW1o1dwZF6I9CXER3O/LGdSzYwiaTDe3LZCA2hvKcvjgKZgIjxctpL0zv2LNp+ICCM05wRDFzzplhwRW3EsQvRkGffaEBFv4PXaE7ahVg3k5YD1SF8zzv2dnEoBBbvqW1/1JwrrE6A91PpQKNGSh8sIasXP/LIv4KFFEq523gZJEbdd69TDdQEUTaZ1+6s7+V+AC0YOtUW2nMTJpB4aqwIZYrU8K1QqTcAEya8iRcfEL+vFrrIPjbeujyIiXnuhqBoI1V8ny/CSsrP2gqcfGEzGLLQeWr9C1p2E9VjlSqOPW1H3sRFfB6O7aFQVt9LlHL4dbywldoJ0xt2exjFtPrsPl/EjAQ4Hju9MTwGjVkPyVybu9UNmi9JWu7gbWsMjXvXHw4/3uSVJKlKaLmKBjYpQ/tVVHnbWk6gakNR11mBZ8M0XMUruUZiAqy21p1SXmj5MtSLgGFUOsFrcu/b4mD94F0um1EHXjnJvctBR2mZun2y+PEMQ9pausop6eFcn3J0u9UfxDh4EeOT8opSE+j4swzi64/Yl7Q58AiDCrdW2CH9GLUebF/9GAadzQS4o/gOY3hfEGxuvTAgrYQEEW37G2yjfXqrnlpnXY6mrReDZ3oF/fsS4baglvH7Io1nIb300Omq1ue8phdBWR/qCsbuI0+8mGtN3Bx8ARu3DpI=
  on:
    tags: true
    repo: gettyimages/gettyimages-api_nodejs
